language: java
jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

services:
  - mysql
  
before_install:
  - mysql -u root --password="" < sql/initdb.sql

script: 
    - >
        bash scripts/build.sh && 
        mvn test -Pcomponent-tests surefire:test &&
        mvn test -Pintegration-tests surefire:test


